"""add github fields to users

Revision ID: b82e11bf3de0
Revises: b6c2d5e8f1a4
Create Date: 2026-09-28 15:30:30.745646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82e11bf3de0'
down_revision: Union[str, Sequence[str], None] = 'b6c2d5e8f1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_name', sa.String(length=255), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'github_authenticated',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column('users', 'github_authenticated', server_default=None)
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_column('users', 'googleAuthenticated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'googleAuthenticated',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column('users', 'googleAuthenticated', server_default=None)
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.alter_column('users', 'avatar',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('users', 'github_authenticated')
    op.drop_column('users', 'github_name')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###
